version: "3"

services:
    web:
        hostname: web
        build:
            context: .
            dockerfile: ./config/backend/Dockerfile
        container_name: web
        command: uvicorn main:app --host 0.0.0.0 --port 8000
        volumes:
          - ./app:/app
        ports:
            - "8000:8000"
        env_file:
            - .env
        restart: always

    redis:
        image: redis:latest
        ports:
            - "6379:6379"

    celery_worker:
        container_name: "celery_worker"
        build:
            context: .
            dockerfile: ./config/backend/Dockerfile
        command: celery -A tasks.celery_worker worker --pool=solo --loglevel=info
        volumes:
            - ./app:/app
        depends_on:
            - redis
            - web
        restart: always

    flower:
        container_name: "flower"
        build:
            context: .
            dockerfile: ./config/backend/Dockerfile
        command: celery -A tasks.celery_worker flower
        volumes:
            - ./app:/app
        ports:
            - "5556:5555"
        depends_on:
            - redis
            - web
            - celery_worker

