version: "3"

services:
    web:
        hostname: web
        build:
            context: .
            dockerfile: Dockerfile.app
        container_name: web
        command: uvicorn main:app --host 0.0.0.0 --port 8000
        volumes:
          - ./app:/app
        ports:
            - "8000:8000"
        env_file:
            - .env
        restart: always
        depends_on:
            - redis
            - celery_worker
            - flower
            - db

    redis:
        image: redis:latest
        ports:
            - "6379:6379"

    celery_worker:
        container_name: "celery_worker"
        build:
            context: .
            dockerfile: Dockerfile.app
        command: celery -A tasks.celery_worker worker --pool=solo --loglevel=info
        volumes:
            - ./app:/app
        depends_on:
            - redis
            - web
        restart: always

    flower:
        container_name: "flower"
        build:
            context: .
            dockerfile: Dockerfile.app
        command: celery -A tasks.celery_worker flower
        volumes:
            - ./app:/app
        ports:
            - "5556:5555"
        depends_on:
            - redis
            - web
            - celery_worker

    db:
        hostname: db
        image: postgres:15
        container_name: database
        volumes:
            - ./data/db:/var/lib/postgresql/data
#        environment:
#            - POSTGRES_DB=myfridge
#            - POSTGRES_USER=myfridge
#            - POSTGRES_PASSWORD=myfridge123
        ports:
            - "5432:5432"
        env_file:
            - .env
